In [ ]:
import pandas as pd
df = pd.read_excel('file/score.xlsx',index_col='지원번호')

In [61]:
# 합계,평균,결과 컬럼을 추가
# 결과 평균점수가 70점이상은 합격, 불합격으로 출력하시오.
df['합계'] = df['국어'] + df['영어'] + df['수학']
df['평균'] = df['합계'] / 3
df['결과'] = '불합격'
df.loc[df['평균'] >= 70, '결과'] = '합격'

In [ ]:
# 컬럼순서변경
# df2 = df[['이름','평균','결과']]
# df2
df = df[['이름','평균','결과','학교','학년', '키', '국어', '영어', '수학', 'SW특기', '합계']]

In [ ]:
# [ cols 리스트 순서를 변경 ]

# 1.리스트 타입으로 변경후 순서를 변경
cols = list(df.columns) 

# cols[-2:] # 평균, 결과 컬럼
# type(cols[0]) # str -> list타입으로 변경하려면 []로 묶어야함
# type(cols[1:-2]) # list 이름 ~ 합계
# 2. 리스트 순서 변경
cols = [cols[0]]+cols[-2:]+cols[1:-2] # str + list + list => error

# 3. 변경된 리스트 적용
df = df[cols]

In [ ]:
# 컬럼수정 - replace,존재하는 컬럼에 값을 입력하면 수정됨
# 컬럼추가 - 없는 컬럼에 값을 입력하면 추가됨
# 컬럼삭제 - drop : 여러개 삭제 가능, inplace=True 적용

In [65]:
df.index

Index(['1번', '2번', '3번', '4번', '5번', '6번', '7번', '8번'], dtype='str', name='지원번호')

In [70]:
filt = df['수학'] > 80
filt.index

Index(['3번', '4번', '5번', '6번', '7번', '8번'], dtype='str', name='지원번호')

In [110]:
df = pd.read_excel('file/score.xlsx',index_col='지원번호')

In [ ]:
# row : index수정,추가,삭제
# index 삭제 - 조건사용해서 삭제
# 수학점수가 80점미만 학생 삭제
filt = df['수학'] < 80
# df2 =df[filt]
# df2

# 컬럼삭제
# df.drop(columns=['평균','결과'],inplace=True) # 컬럼삭제

# [ index row삭제 ]
# df.drop(index=['1번','2번'],inplace=True) # index삭제
# 2. 조건을 이용한 index삭제
# df.drop(index=df[filt].index,inplace=True) # index삭제

In [ ]:
# 1.index추가 : loc[] 이용, 컬럼 개수만큼 입력
# df.loc['9번'] = ['홍길동', '구로고', 190, 90, 80, 70, 60, 50,'Python']

# 2.SW특기 부분 값 추가
# df.loc['4번','SW특기'] = 'C' # index, 컬럼 지정해서 값 입력

# 3. 부분 학교,SW특기 컬럼에 값 수정
# df.loc['4번',['학교','SW특기']] = ['디지털고','python']
# df.loc['5번',['학교','사회','SW특기']] = ['디지털고',50,'Java']

In [113]:
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   구로고  197   90   85  100  95  85      Python
2번    강태원   구로고  184   40   35   50  55  25        Java
3번    강호림   구로고  168   80   75   70  80  75  Javascript
4번    김수찬   구로고  187   40   60   70  75  80         NaN
5번    김재욱  디지털고  188   15   20   10  35  50        Java
6번    박동현  디지털고  202   80  100   95  85  80           C
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON
8번    승근열  디지털고  190  100   85   90  95  95          C#

In [ ]:
df.columns
# 1.국어,영어,수학,과학,사회 합계 컬럼을 추가하고,
# 2.합계점수가 350점이상만 출력하시오.
# 3. 350점 미만 삭제후 출력
df['합계'] = df['국어'] + df['영어'] + df['수학'] + df['과학'] + df['사회']
filt = df['합계'] >= 350
df[filt] # 350점 이상만 출력
df.drop(index=df[~filt].index,inplace=True) # index삭제
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기   합계
지원번호
1번    강나래   구로고  197   90   85  100  95  85      Python  455
3번    강호림   구로고  168   80   75   70  80  75  Javascript  380
6번    박동현  디지털고  202   80  100   95  85  80           C  440
8번    승근열  디지털고  190  100   85   90  95  95          C#  465